
# Note: this file's config overrides the Netlify UI admin config

[context.production]
  command = "npm run netlify:build:production"
  environment = { NPM_FLAGS = "--force --no-progress" }

[context.deploy-preview]
  command = "npm run netlify:build:deployPreview"
  environment = { NPM_FLAGS = "--force --no-progress" }
