
# Note: this file's config overrides the Netlify UI admin config

[context.production]
  command = "npm run build"
  environment = { NPM_FLAGS = "--force --no-progress" }

[context.deploy-preview]
  command = "npm run build"
  environment = { NPM_FLAGS = "--force --no-progress" }
